### ISSUE TITLE
Impossible to modify an ad and add the recipient email address

### ISSUE THREAD

**Issue by mupendara** [litomba/www#107]
It's impossible to modify an ad and add the recipient email address, when we add the address and then save the modification, the recipient address is not saved and not displayed on the detailed ad page.

**Comment by mupendara** [comment]
The email is now saved, but the control of the email address format has been deleted,
Bug reopened

**Comment by AntonioVdlC** [comment]
lol, I love regressions ... 😅

**Comment by AntonioVdlC** [comment]
... actually, was there any validation at all?

As the field is optional I think I just skip the validation ... I should probably look into that!
