### ISSUE TITLE
Change the default picture of an ad

### ISSUE THREAD

**Issue by mupendara** [litomba/www#108]
When an ad is created without the user having uploaded any picture, change the default picture used.
I propose to use the picture representing the size of the parcel.

**Comment by AntonioVdlC** [comment]
mmmh ... I feel like we'll basically duplicate the information with the size icon displayed twice side by side.

I think I'll just work on something real quick. A nice image either with a parcel, or just a text like "No Picture.".

**Comment by mupendara** [comment]
Ok no problem.
I proposed this because it was the most simple and fast thing to do
