### ISSUE TITLE
Notice all the new user that litomba uses cookies

### ISSUE THREAD

**Issue by mupendara** [litomba/www#114]
At the arrival on the landing page, inform the user on the cookies usage, say that it is to help the improvement of litomba service.

**Comment by AntonioVdlC** [comment]
I ain't no lawyer, but I think this means we won't need to get approval for our authentication cookies:

![image](https://user-images.githubusercontent.com/5470315/29947602-c23227a8-8eaa-11e7-8e79-8182a536ba85.png)

(Source: http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm#section_2)

**Comment by AntonioVdlC** [comment]
If you want to, we can always put somewhere in the terms of use that we do use cookies for authentication purposes, but legally we don't have to show a notice or anything!
