### ISSUE TITLE
Ad creation page broken on safari for desktop

### ISSUE THREAD

**Issue by mupendara** [litomba/www#120]
The page layout is broken, moreover when we click on the button suivant nothing happens

![image](https://user-images.githubusercontent.com/30872324/29902360-9ec8226e-8df5-11e7-9896-48ccb57623aa.png)

**Comment by AntonioVdlC** [comment]
I can't reproduce.
Which version of Safari is that? 😮

**Comment by AntonioVdlC** [comment]
(definitely looks like a version of Safari without `flexbox` support 😓 )

**Comment by mupendara** [comment]
Ok the version i use is too old i think, i did not pay attention

![image](https://user-images.githubusercontent.com/30872324/29948275-e1473f3e-8ea5-11e7-9486-10e43420261f.png)
