### ISSUE TITLE
Impossible to create an ad using safari on iPhone 

### ISSUE THREAD

**Issue by mupendara** [litomba/www#121]
It's impossible to input the addressee phone number using safari on iPhone.
When we click on the phone field, we are asked to select the country, once the country is selected w cannot input the phone number.
Everytime we click on the field, we are asked to choose the country code and it's impossible to enter the number.

**Comment by mupendara** [comment]
Ok there is no problem with the phone number anymore, but i still cannot create an ad.
When i click on créer l'annonce, it just scrolls up the page, whereas it should redirects me to the connexion page.

**Comment by AntonioVdlC** [comment]
Can't reproduce on the simulator ... maybe there's an invalid input?

**Comment by mupendara** [comment]
Have you tried to reproduce it using an iPhone finally?

**Comment by AntonioVdlC** [comment]
I finally could reproduce this bug ... working on the solution! 😄
