### ISSUE TITLE
Add the reference of the ad on the summarised ad view page 

### ISSUE THREAD

**Issue by mupendara** [litomba/www#126]
Add the reference of the on the summurised view close to the title of the ad.
I propose to add it using another colour that the title.

Check screenshot
![image](https://user-images.githubusercontent.com/30872324/29968685-c1c29914-8f14-11e7-96da-76e2fb8ddba5.png)

**Comment by mupendara** [comment]
The reference has been added, but the way it is displayed is not visible enough.
I think the reference is as important as the parcel name. Both should be displayed in the same font size (or barely smaller), the same boldness and in the same "area" but in a different colour to make the user understand that they are different types of information (parcel name and ad reference).
I would then move the reference field close to the parcel name, starting with "Ref." as you have displayed it in the ad page.

What do you think?
![image](https://user-images.githubusercontent.com/30872324/30002262-0a130ae4-909d-11e7-9225-f348f4301cd7.png)

**Comment by mupendara** [comment]
@AntonioVdlC  Why did you close this card?

**Comment by AntonioVdlC** [comment]
oh lol, sorry, that's automatic when I merged `dev` into `master` as I referenced this issue in a commit 😅
