### ISSUE TITLE
Add the subscription to news on the "Je voyage" text

### ISSUE THREAD

**Issue by mupendara** [litomba/www#128]
On the landing page, the same link as the one of the "a venir" button should be present on the "je voyage" label.
Basically, when a user clicks on Je voyage, the field to input his email address should appear.

**Comment by AntonioVdlC** [comment]
Isn't that the case already? 🤔

**Comment by mupendara** [comment]
Loool, yes you are right. Soeey

**Comment by AntonioVdlC** [comment]
No problem! 😝
