### ISSUE TITLE
Problem on on-boarding page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#131]
When a user registers for the first time, when he clicks on the terms and conditions link on the on-boarding page, a new window displays the terms and conditions but on the main window the user is redirected on the detailed ad page.
The user should no be redirected as he as not accepted the terms and conditions, and he has not clicked on the save button of the on boarding page.

**Comment by AntonioVdlC** [comment]
Wait ... what? 😱

Which parcel details page? ... I seriously have to see it to believe that!

**Comment by mupendara** [comment]
The ad page.

**Comment by AntonioVdlC** [comment]
Like, the ad creation page?

**Comment by mupendara** [comment]
Ad details page, the detailled ad visualisation page.

**Comment by AntonioVdlC** [comment]
Which ad? I really don't understand how that is even remotely possible if the database is empty? How can there be already an ad to visualise?

Besides the fact that there is absolutely no way I can think of to go from the on-boarding screen to an ad page.

Can we make a quick call this afternoon so you can show me what's happening? 🙂

**Comment by mupendara** [comment]
It's because i started by ad creation, then i've been redirected to connexion page, i connected/sign up through Facebook, then i've been redirected to on-boarding page, then the bug happened.

**Comment by mupendara** [comment]
Can you clean the database so i can retry to reproduce it?
I need to register.

**Comment by AntonioVdlC** [comment]
Okkkk!!!

That definitely makes much more sense, and effectively that thing with the ad creation and the on-boarding is not completely smooth yet.

It seems like opening the terms actually clears the localstorage holding the ad information.
