### ISSUE TITLE
Problem with the placeholders of the landing page using Galaxy S7

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#147]

**Comment by mupendara** [comment]
Problem of layout on the on-boarding page using chrome on a Galaxy S7 phone

**Comment by mupendara** [comment]
![img_20170904_152519](https://user-images.githubusercontent.com/30872324/30031105-115e1186-9188-11e7-9e23-cd606f673a31.jpg)

**Comment by AntonioVdlC** [comment]
It should now be ok for phones as small as 290px of width ... if someone comes with a phone smaller than that, I'll buy him/her a new one for reals! 😅

**Comment by zuluzaire** [comment]
Now that we've changed the font, the problem reappeared.
I see it on my phone, and on all the hotjar sessions using phones.
See an example here: http://insights.hotjar.com/p?site=644709&recording=888513628

**Comment by AntonioVdlC** [comment]
Lol, that's why it is advised to use labels to convey information on what the user should input instead of placeholders ... 😅
