### ISSUE TITLE
Add an underline below the "Mode d'emploi" label

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#155]
## Description

Add an underline below the mode d'emploi label so visitor can understand that it is possible to click on the link.
I had feedbacks saying that some people is not used to the internet and did not get that the label was clickable.

## Steps to reproduce / User Story

1. Display the landing page

### Operating System
- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS

### Browser
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] Opéra 
- [ ] Internet Explorer

## Notes
I know it my be obvious for us... But we are used to browse the internet everyday, it's not necessarily the case of our target customers !!

**Comment by AntonioVdlC** [comment]
I ended up putting a border ... I think it is more visible than an underline!

| Before        | Border           | Underline  |
| ------------- |------------| -----|
| ![localhost-3000- 1](https://user-images.githubusercontent.com/5470315/30057526-51a8fe68-9237-11e7-8e10-4f95f326ca60.png) | ![localhost-3000-](https://user-images.githubusercontent.com/5470315/30057536-5c72e412-9237-11e7-848a-41dd3ced1d96.png) | ![localhost-3000- 2](https://user-images.githubusercontent.com/5470315/30057544-65cda7f4-9237-11e7-8d13-c0a8f4f64c90.png) |

**Comment by zuluzaire** [comment]
I like the border, good idea 👍
