### ISSUE TITLE
How To for travelers

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#158]
Add the how to for travelers in the mode d'emploi page

**Comment by zuluzaire** [comment]
Modify the following texts:
1- "Trouver un colis à transporter"
2 - "Envoyer une proposition de livraison au créateur d'une annonce dont vous êtes intéressés, afin de transporter son colis et gagnez de l'argent."
3- "Lorsque votre proposition est acceptée par l'expéditeur, vous accédez à ses coordonnées ainsi qu'à celles du destinataire du colis."

**Comment by zuluzaire** [comment]
I know i wrote and made you display this sentence, but does it sound event french?
"Envoyer une proposition de livraison au créateur d'une annonce dont vous êtes intéressés, afin de transporter son colis et gagnez de l'argent."

Maybe "Envoyer une proposition de livraison au créateur de l'annonce dont vous êtes intéressé, afin de transporter son colis et gagnez de l'argent."

Or "Envoyer une proposition de livraison au créateur de l'annonce à laquelle vous êtes intéressés, afin de transporter son colis et gagnez de l'argent."

What do you think?
Sorry for the rework though :s

**Comment by AntonioVdlC** [comment]
Envoyez une proposition de livraison au créateur de l'annonce qui vous intéresse afin de transporter son colis et gagner de l'argent.

? 🙂
