### ISSUE TITLE
Checkbox not checking on Firefox Mobile

### ISSUE THREAD

**Issue by AntonioVdlC** [litomba/www#166]
## Description

The checkbox in the on-boarding page does not seem to work on Firefox Mobile for Android.

## Steps to reproduce / User Story

1. Go to the on-boarding page
2. Try to check the terms and conditions
3. ...
4. Nothing happens!

### Operating System

- Android

### Browser

- Firefox

## Notes

Reproduces on Firefox Mobile for Android (55.0.2)
Probably a bug from their side as the state of the checkbox does update, but the UI stays the same.

**Comment by zuluzaire** [comment]
The behaviour has change but the checked check box is still strange.
Instead of a check or a cross, the case is filled with blue colour.
Is it possible to have a cross or it's native from firefox?

**Comment by AntonioVdlC** [comment]
It's a best-effort ... 😅 
It makes it functional, and I think we have bigger fishes to fry right now!
Besides I don't think we'll have a lot of users using Firefox Mobile 😜

**Comment by zuluzaire** [comment]
Yes you are right. Let's keep it this way.
