### ISSUE TITLE
Improve the description of fields at all time in ad creation page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#168]
## Description
In the creation page, users do not understand clearly how to fill each field.
Display the help instructions in permanence (currently appearing after clicking on the "i" button).
Remove the info button.

## Steps to reproduce / User Story
1. Display the description of each field of the ad creation page at all time
2. Remove the "i" button for each field

### Operating System
All environment, mobile and desktop.

**Comment by AntonioVdlC** [comment]
If I remember correctly we talked about displaying the hints on desktop but keep it hidden on mobile, is that right? 🙂

**Comment by zuluzaire** [comment]
Yes but I changed my mind and i think we should display it on the mobile too.
