### ISSUE TITLE
Modify the description of the addressee phone number field in the ad creation page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#172]
## Description
Users do not understand how to fill the phone number field, they do not understand that country code is mandatory.

## Steps to reproduce / User Story

1.  Add the mention that the country code is mandatory in the label description
2.  Add a country code field where the user can select the country and the country code will be filled automatically (or something else)

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
For now just adding a text in the hint and error about the country prefix.
