### ISSUE TITLE
Modify the label on the landing page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#179]
## Description

Sur la landing page, ajouter du texte de façon à expliquer les avantages à utiliser litomba.
Actuellement l'utilisateur n'a aucun indication sur les avantages à utiliser notre plateforme.

## Steps to reproduce / User Story

1. Modify "Envoyez vos colis vers l'Afrique avec litomba !" label to "Envoyez vos colis vers l'Afrique sans effort !!" 
2. Modify "Gagnez de l'argent en transportant des colis" label to "Gagnez de l'argent facilement avec vos bagages !!"
3. Modify "Profitez de la place des gens qui voyagent" to " Utilisez un service simple, rapide et efficace pour envoyer vos colis"
4. Modify "Recevez une notification lorsque cette fonctionnalité sortira !" label by "Rentabilisez vos frais de voyage en utilisant la place dans vos bagages"

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by zuluzaire** [comment]
Only the 1) has been treated.
The other labels have not been modified, is it on purpose?
I reopen the card.

**Comment by AntonioVdlC** [comment]
This is what I see in preprod right now ... am I missing something? 😅 

![litomba-mvp herokuapp com- 1](https://user-images.githubusercontent.com/5470315/30323403-64a63d4c-97bd-11e7-9d71-f5cffd9509a3.png)
