### ISSUE TITLE
Problem with the buttons on the landing page 

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#181]
## Description

On the landing page, the expédier and valider buttons are not aligned anymore with the input field.
But the design of landing page is totally changing anyway, so maybe it's not necessary to fix this bug?

## Steps to reproduce / User Story

1. Access to the landing page

### Operating System
Mobile and desktop

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

## Notes

![image](https://user-images.githubusercontent.com/30872324/30317632-90e2981c-97a2-11e7-87b5-8d34dc0919da.png)

**Comment by AntonioVdlC** [comment]
Argh ... my bad! I wasn't really awake last night ... really sorry about that! 😓
