### ISSUE TITLE
Problem with the keyboard overlaying some field using the mobile

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#198]
## Description

On the ad creation page using a mobile, the keyboard overlays some field sometimes.
Check the screenshot.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by zuluzaire** [comment]
![screenshot_2017-09-14-21-46-30](https://user-images.githubusercontent.com/30872324/30456004-d4141d38-9999-11e7-8ed8-074fe000c31d.png)

**Comment by AntonioVdlC** [comment]
mmmh ... usually it's the phone's job to make sure the input is visible when the keyboard is up! 🤔 

I haven't been able to reproduce it on my phone, so I don't think I can do much in here, sorry ...
