### ISSUE TITLE
Problem at access to "Mes colis" page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#201]
## Description

When a user deletes all his parcel ads, when he tries to access to "Mes colis" page, the page loads continuously without never ending.
The page should not load without never ending, it should display a message saying there is no ad.

## Steps to reproduce / User Story

1. Connect as a user
2. Delete all you ads (if the user doesn"t have any ad, create one and delete it)
3. Access to "Mes colis" page

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Oops, my bad!
This is a regression due to a missing string ... 😅
