### ISSUE TITLE
Add more sign up methods

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#206]
## Description

Currently it's only possible to sign up using facebook which is quite restrictive for our target users, add either of the following:
- login/password sign up,
- email sign up.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Ready for QA! 🙂 

Just a few TODOS:
- i18n strings
- default profile pic
- merge back to `dev`

**Comment by zuluzaire** [comment]
The email address placeholder is not entirely readable, check below
![image](https://user-images.githubusercontent.com/30872324/31636353-026e40d2-b2c2-11e7-9ee2-c6a59745282c.png)

**Comment by zuluzaire** [comment]
The description text should be changed to 
"Vous avez le choix entre 2 options pour vous connecter:"
![image](https://user-images.githubusercontent.com/30872324/31636414-4042db52-b2c2-11e7-8120-83bf030e7471.png)

**Comment by zuluzaire** [comment]
What happens if the user clicks 15 minutes later on the link in the activation email ?

**Comment by zuluzaire** [comment]
Update the notification message label to
"Pour vous connecter cliquez sur le lien dans le mail que vous avez reçu à l'adresse [MAIL ADDRESS]"

Check below
![image](https://user-images.githubusercontent.com/30872324/31636873-217a4a3c-b2c4-11e7-80c4-9f565258bbb8.png)

**Comment by AntonioVdlC** [comment]
- Add analytic events

**Comment by zuluzaire** [comment]
Add the date and time of the connexion request in the title of the connexion email so the email is not clustered in the same conversation in the mail client.
Check beloz

![image](https://user-images.githubusercontent.com/30872324/31636947-7461e78c-b2c4-11e7-8686-adc11cbf2f64.png)

**Comment by zuluzaire** [comment]
In terms of layout, let's learn from the best :))))
Is it possible tu use a facebook designed like button with a Airbnb like design? (horizontal seperation between fb and email instead of vertical)

**Comment by AntonioVdlC** [comment]
All done except the email title thing ... 😅 
I feel like that'd be ugly and quite unnecessary as, at least GMail, seems to only create threads if you send a lot of messages on the same day. In theory once you're logged in y'all set!

**Comment by zuluzaire** [comment]
Could you erase paul.junior.kasseyet@gmail.com so I can test it ?

**Comment by AntonioVdlC** [comment]
TODO
- Error handling
- Facebook linking (make sure only one Facebook account in all litomba accounts)
