### ISSUE TITLE
Add the company registration in the terms and condition page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#208]
## Description

At the beginning of the terms and condition page, add the registated name and registration number of the company

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Mmmh ... where exactly should I add that and what exactly should I add? 😅

**Comment by zuluzaire** [comment]
Je pensais à un truc simple comme ça avec le nom de la compagnie, le numéro de registration et c'est tout :)

![screenshot_2017-10-04-18-58-04](https://user-images.githubusercontent.com/30872324/31191436-015c9fe4-a936-11e7-86d3-5f92060cd573.png)
