### ISSUE TITLE
Add a notification at ad creation

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#213]
## Description

After the user has created an ad, add a text to inform the user that his/her ad has been created.
The text should be visible, and could disappear (notification behaviour).

Proposition: It could be a sort of little box appearing on the middle of the ad details page with a "Ad created" text, a close button and the box be disappearing after 5 seconds.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
I have also added a button to create another ad! 🙂

**Comment by zuluzaire** [comment]
The look and feel with the blue band on the bottom of the header looks strange...

![image](https://user-images.githubusercontent.com/30872324/31142530-7c59e73e-a872-11e7-88b8-2892f0d2dec3.png)

**Comment by AntonioVdlC** [comment]
It's the exact same thing as when you update your profile information ...
Maybe the button should be in another color?

**Comment by zuluzaire** [comment]
Is it ?
![image](https://user-images.githubusercontent.com/30872324/31142923-9ce07dd2-a873-11e7-81f7-e659136469b4.png)

**Comment by AntonioVdlC** [comment]
Yep? 😅 

![image](https://user-images.githubusercontent.com/5470315/31143011-3b1cfa0e-a87c-11e7-8c97-d46e8c3c6751.png)

**Comment by zuluzaire** [comment]
True
Well i think it is the height of the blue band that is disturbing...
Maybe if we put the notification message and the button on the same line ?

**Comment by AntonioVdlC** [comment]
Is this better? 🙂 

![image](https://user-images.githubusercontent.com/5470315/31184062-a78aafae-a928-11e7-883d-e0a1b63fe9cb.png)

**Comment by AntonioVdlC** [comment]
I have also added an analytic event on that button! 😛

**Comment by zuluzaire** [comment]
La notification en haut de page est cool sur le mobile at least, i need to double check on the desktop.
In term of UX, dontyou think thst the create a new ad button would be better at the botto' of the ad?

On my mobile i scrolled down to have a look at my ad, and had to actually scroll up again to access to that button. 
I feel like it's more natural to have it down in the page?
