### ISSUE TITLE
Issue when I create an ad without being logged inf

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#215]
## Description

When i create an ad without being logged in, when i click on log after the ad creation, i am redirected to the landing page. When I click on "Créer un annonce" from the landing page, I am redirected to the ad visualisation page for the ad I previously created.

## Steps to reproduce / User Story

1. 
2.
3.
4.

## Environment

MVP

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Wow, that sounds wild!
I've had some issue today with infinite redirections, but I thought that was due to a dirty state somewhere as relaunching the website did the trick ... 😕

**Comment by zuluzaire** [comment]
I tried it again on my desktop, and i was not able to reproduce it.
But i am 100% sure it did happen.

**Comment by AntonioVdlC** [comment]
ok, I wasn't able to reproduce it today, but I have seen that behaviour too so I believe you ...
let's just tag this and move on!
