### ISSUE TITLE
Confusion on the telephone number input

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#219]
## Description

On the telephone number input, users are confused and try to click on the button for flag first before entering the telephone number.
As you proposed, we can redirect the cursor on the input field when they click on the button for flag.

This should be implemented everywhere there is a phone number input in the product.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
> As you proposed, we can redirect the cursor on the input field when they click on the button for flag.

That was actually already the behaviour we had ... so instead I just erased the flag from the input! 😅
