### ISSUE TITLE
User rating missing on the ad search result page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#224]
## Description

On the ad search result page, the rating of the user who has created the ad is not displayed.
The following information should be displayed in order to highlight the trust on litomba:
- User average rating,
- Number of comments.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by zuluzaire** [comment]
Replace the label by "note - nombre d'avis"
When there is non of them, display "-/5 - 0 Avis"

**Comment by AntonioVdlC** [comment]
I can actually change the text to French (oops, my bad), but I think it won't be a good idea to change it to "-/5 - 0 avis." It's confusing and doesn't provide more information than just "Aucun avis."

Here's how it looks like with some ratings:
![image](https://user-images.githubusercontent.com/5470315/32139031-167a5daa-bc3f-11e7-886a-a0445d929fd7.png)

**Comment by zuluzaire** [comment]
Yes you are right.
You can write "Aucun avis" (without a "." at the end).

I am wondering if the red colour is not too "agressive" for this information on the page.
