### ISSUE TITLE
Add an easy way to perform a new search from the ad search result page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#227]
## Description

From the ad search result page, currently the user cannot perform a new search except by using the browser navigation button.
The user should be able to easily perform a new search either by directly changing the search criteria displayed on the user page, or adding a "Retour" button to go back to the search page (not ideal at all but if it is less time consuming, it will be enough for now).

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
The "Retour" button should already be there! 😝

**Comment by zuluzaire** [comment]
I need to double check, but if i did not see it, probably means it was not obvious enough?
