### ISSUE TITLE
Change the label of the button on some landing page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#228]
## Description

On the landing pages home4 and home3, the green button to access to the ad creation page use the words "creer une annonce" instead of "Envoyez un colis".
From the hotjar recording, I think the shipping wording leads users to start creating an ad.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Well, that was the point of having different versions I guess: try to see which wording/style would lead to more ad creations! 🙂 
If we have enough data to discard some of the versions, then we can go ahead and erase them!

**Comment by AntonioVdlC** [comment]
Irrelevant with the new landing page.
