### ISSUE TITLE
Add link to social media 

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#241]
## Description

Social media links are missing on litomba.
In the footer, we could add the logo of twitter and facebook to redirect to our social media accounts.
(www.facebook.com/litomba and www.twitter.com/litomba)
We could add a "Share via facebook" button too.

The problem with the footer is that only few people scroll to the end of the page.
Should we add the "share via facebook"  in the header then? And the facebook and twitter logo to the header?
What do you think?

Regarding the design of the buttons, let's use flat icons, and use the colour of litomba (blue, green, red or white...)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by zuluzaire** [comment]
Nice one !!!
I like the way the footer looks, nice job :)

What about the "share to facebook" button though?

**Comment by AntonioVdlC** [comment]
Mmmmh ... I think that's not really important for now!
Maybe further down the line when we'll have the whole thing working?

I can see a "Share to Facebook" button on ad creation, but again, that'd be more effective once we also have the traveler side up and running! 😛

**Comment by zuluzaire** [comment]
I think the "share via facebook" button can help us in term of visibility.
Basically, the visitor would share litomba on their facebook timeline with a status pre-registered by us.

And I would not add the share via facebook button for each ad created, because if somebody creates an ad and share it via facebook, people would contact them directly without passing through litomba.

**Comment by AntonioVdlC** [comment]
Oops, closed automatically sorry ... 😅
