### ISSUE TITLE
Problem at connexion using facebook

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#242]
## Description

From the landing page, i clicked on "connexion" then connected using facebook.
It had me connected and directly redirected me to the ad visualisation page for a previous ad Ive had created before.
I also received the ad creation email.

Is it related to a problem with the cache?

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Yeah, that's due to the persistence of `localStorage`! Changing it to a `sessionStorage` seems to do the trick! 🙂
