### ISSUE TITLE
Enhance the notification message after the creation of an ad

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#243]
## Description

I've seen a user confused after his/her ad was created. See here: http://insights.hotjar.com/p?site=644709&recording=911629244

After the creation of an ad, on the notification message, mention that a confirmation email has been sent to the [email address].

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
I think more than that, it'd be helpful to tell the user what to expect next, such as `Vous recevrez des propositions de livraison par email sous peu !`?
