### ISSUE TITLE
Problem at connexion

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#245]
## Description

What could cause this type of problem of connexion? See session below
http://insights.hotjar.com/p?site=644709&recording=913759635

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
It might be due to the fact that the user went in Facebook to connect, but then cancelled it.

I found this in the logs:
```
Oct 20 17:29:48 litomba heroku/router:  at=info method=GET path="/auth/facebook/callback?error=access_denied&error_code=200&error_description=Permissions%20error&error_reason=user_denied" host=www.litomba.com (...)
```

**Comment by zuluzaire** [comment]
ok cool
