### ISSUE TITLE
End to end ad creation process is broken

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#250]
## Description

Currently when the user creates an ad, connects using his/her email then clicks on the email activation link, he arrives on the landing page instead of arriving on the ad visualisation.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by zuluzaire** [comment]
Corrected

**Comment by zuluzaire** [comment]
The button link in the

**Comment by zuluzaire** [comment]
J'ai un peu testé tous les scénarios, dans l'ensemble ça fonctionne sauf le scenario ci-dessous.

Lorsque je crées une annonce et que je me login en utilisant mon email depuis mon mobile, lorsque je clique sur le lien présent dans l'email depuis mon ordinateur, je suis redirigé vers la page d'accueil au lieu d'être redirigé vers mon annonce créée.

Je pense que ce sera un scenario fréquent, de changer de device entre l'inscription en utilisant l'adresse email et le click dans l'email recu.
Je réouvre le ticket, grosse priorité !

**Comment by AntonioVdlC** [comment]
Moving this to `MVP 2` ...
