### ISSUE TITLE
Redirection to the ad visualisation page missing after connexion at ad search

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#251]
## Description

When an unlogged user performs a search, when he clicks on an ad in the search result he is asked to log in in order to visualise the ad.
When the user connects using facebook, he is redirected to the home page.
The user should be redirected to the visualisation page of the ad he originally clicked on.

The behaviour should be the same when the user decides to login using his/her email, when he/she clicks on the URL present in the email he receives, he/she should be redirected to the ad visualisation page for the ad he originally clicked on.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Waiting for #250 to be merged into `master` and back into `mvp-2`.
