### ISSUE TITLE
Modify the placement of the notification at connexion using an email on mobile

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#252]
## Description

On the login page when the user enters an email address the notification message saying he/she will receive an email is displayed on top of the page.
On the mobile, when the user clicks on "s'inscrire" as it is scrolled down the notification is not visible, and the user does see think there is a bug.

Proposition, when the user clicks on "s'inscrire", redirect him to the top of the page so he can see the notification.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
I also corrected a few stuff concerning error handling, when for example inputing a wrong email address!
Also, now you can submit by pressing on Enter (instead of having to clic on the button)!
