### ISSUE TITLE
Change a label in the header menu

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#265]
## Description

Change the label in the header menu from "Connexion" to "Se connecter".
Put this label at the bottom of the menu.
Why is it in green colour ? 

![image](https://user-images.githubusercontent.com/30872324/32144281-6233b34e-bcae-11e7-8211-6ea9e63138d0.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
The `Déconnexion` one is in red so I thought it'd be a good idea to have the `Connexion` one in green. ... 😅

**Comment by zuluzaire** [comment]
lol ok cool.
