### ISSUE TITLE
Change the position of sections in the "mes colis" page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#287]
## Description

On the "mes colis" page, change the position of parcels with proposition pending so they are displayed on top of the list.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Mmmh ... I don't think people will have as many parcel ads as we have in our testing environments.

And if they did, I don't think changing the order would be best as you'd loose some of the logical progress of a parcel (creation > proposition > delivery).

I think we can park this one for now, and maybe look at implementing a form of small menu or filtering down the road?

**Comment by zuluzaire** [comment]
Ok i agree
