### ISSUE TITLE
Change the label of a button

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#297]
## Description

Change the label on the button in the image below to "Entre le code d'expédition"

![image](https://user-images.githubusercontent.com/30872324/32629859-882694ee-c592-11e7-8ff0-8cc0db779f6d.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
I'm afraid that'd be too long, and maybe a bit misleading?
The action on the next page is to confirm the pick up, and to do so to input a code, but that is quite explicit on the next page!

**Comment by zuluzaire** [comment]
ok
i agree
i close the ticket
