### ISSUE TITLE
Acceptation date missing in the proposition page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#299]
## Description

In the proposition page, the sender should be able to see the date (and time?) he accepted the proposition of the user.

See image below
![image](https://user-images.githubusercontent.com/30872324/32630097-56b26b76-c593-11e7-8e7b-82cbbdddfe59.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Adding that on the parcel details screen sounds more useful to me, as a sender would not be able to see this page once the proposition has been accepted ... 😅
