### ISSUE TITLE
Problem of redirection

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#301]
## Description

From the porter un colis-How to Page, when the user click on "Trouver un colis", the user is redirected to the search page but at the bottom of the bottom of the page (scrolled down).
The user should be redirected to the search page but at the top of it.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
I just made a quick fix on this one, but I may look into it more precisely and maybe do some refactoring to apply that change to all the screens!

**Comment by zuluzaire** [comment]
ok
