### ISSUE TITLE
Change label in Confirmer code d'expedition page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#306]
## Description

In the confirmer code d'expedition page, change the label in the image below by "Code d'expédition"

![image](https://user-images.githubusercontent.com/30872324/32631362-ef054f20-c597-11e7-8730-d46e990bca5f.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
I think that information is already in the title (and it should probably be `Code de livraison` in this particular case 😅).

**Comment by zuluzaire** [comment]
ok i agree
i close the ticket
