### ISSUE TITLE
Impossible to perform a ad search

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#308]
## Description

When the user inputs the name of a start city, a message talking about technical object is displayed .

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by zuluzaire** [comment]
![image](https://user-images.githubusercontent.com/30872324/32699864-46d453fe-c7b4-11e7-8e45-c2a3f51059c3.png)

**Comment by AntonioVdlC** [comment]
Oops ... my bad! 😅
