### ISSUE TITLE
Problem with the process flow when a user wants to visualise an ad

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#312]
## Description

Redirection problem

## Steps to reproduce / User Story

1. When the visitor clicks on an ad, he is redirected to the login page.
2. When he logs in using his email, he/she receives an email with a button to log in.
3. when he clicks on the button he is logged but redirected to the landing page instead of the ad visualisation page of the ad he clicked on.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Can this be a duplicate of #311 ?

**Comment by zuluzaire** [comment]
No it's not ! One is for the proposition the other is for ad visualisation

**Comment by AntonioVdlC** [comment]
Mmmh ... ok, because both description are about ad visualisation! 😅

**Comment by zuluzaire** [comment]
my bad.
But it works now !!
