### ISSUE TITLE
Impossible to select Abidjan as end city

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#315]
## Description

There is an error when the user selects Abidjan as end city in the search page.
It's important to check because it is the value of the placeholder for the field ^^"

![image](https://user-images.githubusercontent.com/30872324/32747463-afc77830-c8b0-11e7-8cf1-8cdc2ee58215.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Lol, funnily enough `Abidjan, Lagunes District, Côte d'Ivoire` does work but not `Abidjan, Côte d'Ivoire` because for some reason it doesn't recognize Abidjan as being a city in the second query ...

**Comment by zuluzaire** [comment]
What was the problem finally? How did you correct it?

Will we have the same problem with other cities?

**Comment by AntonioVdlC** [comment]
Basically it means that I'm looking beyond the city and first administrative districts that Google sends me back.
