### ISSUE TITLE
Impossible to accept a delivery proposition - ERROR 403

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#316]
## Description

When a sender receives a delivery proposition, from the proposition page when he clicks on "Accepter la proposition" there is an 403 ERROR in the console and nothing happens.
See image below

![image](https://user-images.githubusercontent.com/30872324/32747866-18095d04-c8b2-11e7-82fd-0fa8e55a1eeb.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Mmmh ... ok, so the error here is that you can accept or reject the proposition being the traveler ...
