### ISSUE TITLE
Change a label on the proposition page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#317]
## Description

Change the label in the image below to "Coursier"

![image](https://user-images.githubusercontent.com/30872324/32747988-9a99ecde-c8b2-11e7-92d8-283f5086d150.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Already done ... I guess I forgot to put that in the QA column, my bad! 😅
