### ISSUE TITLE
Retrieve payment information for travelers

### ISSUE THREAD

**Issue by AntonioVdlC** [litomba/www#319]
## Description
We need to find a way to pay travelers after deliveries (ahem 😅 ), so for now we can ask them for payment info the first time they send a proposition (if we don't already have one) such as a PayPal account or a bank account.

## Steps to reproduce / User Story
1. A traveler sends a proposition
2a. If the traveler already has a payment method registered the proposition is sent
2b. Else we ask the traveler to provide a PayPal account or a bank account and we save that for ulterior payment

## Notes

Manual work FTW!

**Comment by zuluzaire** [comment]
True !!
I thought about the same thing.

These are the information we need to add a new counterparty;

- Country
- Currency
- IBAN reference
- BIC reference
