### ISSUE TITLE
Ad not displayed in ad search result

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#340]
## Description

An ad respecting the search criteria is not displayed in the search results.

## Steps to reproduce / User Story

1- I have just created ad FRCD-5FG26FAJ from Paris (Chateau rouge) to Kinshasa 'Ndjili airport), XL size on my desktop with my logged with facebook user.
2 - I clicked on modify ad, i did not change anything and I saved.
The start and end addresses switched to Paris and Kinshasa, the exact addresses been removed only the city remains.
3 - When I search using my mobile with my logged with email user on Paris to Kinshasa, XL size, I see all the parcels respecting my criteria except the one I have just created.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by zuluzaire** [comment]
I still cannot see the ad when I search

**Comment by AntonioVdlC** [comment]
The data is corrupted, please try with another ad!

**Comment by zuluzaire** [comment]
ooooooooooook

**Comment by AntonioVdlC** [comment]
Basically when you were editing an ad, the origin and destination information were lost. So it shouldn't be the case anymore, but for that ad the data is gone so I can't do much about it ... 😅

**Comment by zuluzaire** [comment]
ok i deleted that ad so i am not confused later or so
