### ISSUE TITLE
Impossible to confirm the delivery

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#344]
## Description

An error message is displayed when I try to validate the delivery with the delivery code for the ad FRCD-UHPC9FAJ on my mobile. (used to work fine before).
See images below
![image](https://user-images.githubusercontent.com/30872324/33230888-64b5043e-d1e3-11e7-8ad3-b5ff1ec68ae5.png)

![image](https://user-images.githubusercontent.com/30872324/33230893-824d1ffe-d1e3-11e7-8285-a29aaf285e18.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Ok, seems like I forgot to remove some Braintree code which caused the error ... try again in 5-10 minutes! 
Sorry about that!

**Comment by zuluzaire** [comment]
The problem is still present.
The behaviour is exactly the same.

**Comment by AntonioVdlC** [comment]
Looking at the logs, it seems like you inputed the pickup code instead of the delivery code ... try with the following code: `125674`!

**Comment by zuluzaire** [comment]
ok !!!!!

**Comment by zuluzaire** [comment]
Used the wrong code fro the wrong ad.
Works fine
