### ISSUE TITLE
Remove delivery proposition accepted ads from ad search results

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#347]
## Description

Ads for which delivery has been accepted should not appear in the ad search results.

OR a mention should be displayed saying the sender has accepted the proposition of [display name and picture of the traveller] 
In that case, the traveller searching for ads to deliver can see that there is activity on litomba platform.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
Isn't this already the case? 🤔 

Parcels that have been delivered or which propositions have been accepted don't appear in the list of search results (or if they do that's a bug in the code! 😅 ).
