### ISSUE TITLE
Delivery proposition

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#35]

**Comment by AntonioVdlC** [comment]
TODO
- Send email on proposition to the sender and the traveler
- List the propositions on the sender parcels list and traveler deliveries list
- Accept a proposition and create a `delivery` and verification codes (+ notify sender, traveler and receiver)

**Comment by AntonioVdlC** [comment]
TODO
- Filter out ads the traveler has already sent a proposition to.
