### ISSUE TITLE
Impossible to pay for a delivery using Stripe

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#354]
## Description

When I input the information of the credit card, there is an error coming from stripe.
Check image below

![image](https://user-images.githubusercontent.com/30872324/33284670-c0e95cd0-d3a7-11e7-8ca8-fdc86f2f819a.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment]
I need to investigate more into why the env variable worked in dev and not in prod, but I pushed a quick and dirty fix for this! 

Should be working now! 🙂
