### ISSUE TITLE
Add a "resend code" function

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#355]
## Description

The sender should be able to request for litomba to send again the code (code expedition or code livraison).

The button should be displayed on the ad pre-visualisation screen in the "mes colis'" page or on the ad visualisation screen when the sender visualise an ad which proposition have been accepted and for which delivery have not been confirmed yet.

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by zuluzaire** [comment]
The code is correctly resent when the user requests it but,
A notification message is missing when the user clicks on the resend button.

Add a notification message confirming the code have been resent, and suggesting the user to check his emails.

**Comment by AntonioVdlC** [comment]
... this seems like a trivial chance, but it ain't because of how I coded it! 😅 

May need to refactor all that part at some point, because it's starting to become quite a mess ... 😬
