### ISSUE TITLE
Enhance the description for the phone field input

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#360]
## Description

Users seems to be struggle to register because of the phone field.
Example of user struggling (one of many): https://insights.hotjar.com/p?site=644709&recording=1005637449 

It prevents some users from creating their accounts, basically we loosing users :s that's why it's 

## Steps to reproduce / User Story

1. Change the hint to:
"Veuillez vérifier votre numéro de téléphone en indiquant l'indicatif du pays.
Ex; +33 pour la France"

2. When the indicatif is missing, change the error message to:
"Veuillez indiquer l'indicatif du pays, +33 par exemple"

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by zuluzaire** [comment]
I dont see any change compared to before?

**Comment by AntonioVdlC** [comment]
The hint and error message were pretty much already there ... I mean I can copy-paste your text, but it's pretty much the same?
I did change the ones on the user profile though because they didn't say anything about the country code.
