### ISSUE TITLE
Users having difficulty logging in with email

### ISSUE THREAD

**Issue by AntonioVdlC** [litomba/www#369]
## Description
Users seem to have troubles connecting with email.
This can be due to the short (15 minutes) validity of the tokens, or the fact that users keep reusing the same token.

## Steps to reproduce / User Story
1. Log in with email
2. ...

## Possible Solution

A quick solution could be to enlarge the validity time of tokens, and also to have more explicit error messages!

**Comment by zuluzaire** [comment]
Most of our user will not know what a "token" is.
Change the text from "le token...." to "Le lien de connexion a expiré."
