### ISSUE TITLE
Change landing page text to cater to travelers

### ISSUE THREAD

**Issue by AntonioVdlC** [litomba/www#370]
## Description
Some users have sent us feedback telling us litomba seems more catered to sender than travelers.
While it's true we have been pushing forward features for senders to gather more ads, it can be interesting to switch to travelers to try and get some transactions going!

## Steps to reproduce / User Story

1. Go to the landing page
2. Be confused!
3. ...

## Notes

A possible solution here would be to change to text and button at the top of the landing page to target travelers!

**Comment by zuluzaire** [comment]
The changes on the landing page when the user is connected is nice.
But I had in my that it should be the case for not connected users as well, shouldn't it ?

**Comment by AntonioVdlC** [comment]
Oops, sorry forgot about that one ... 😅

**Comment by AntonioVdlC** [comment]
... wait, that's already the case (or I'm really missing something here)

**Comment by zuluzaire** [comment]
I was talking about the changes in the buttons, i should have been more precise :sssss

![image](https://user-images.githubusercontent.com/30872324/34251386-368e9900-e640-11e7-879e-3bd22576056d.png)

**Comment by AntonioVdlC** [comment]
Well, that was already the case in the previous version of the landing page wasn't it?
The idea was that we had a lot of people just bouncing out of the landing page, and that at least we wanted to get some to at least sign up.

Would you like to have the same buttons for both logged-in and logged-out?

**Comment by zuluzaire** [comment]
hmmm
the inscription button was more for when we did the article, the objective was to have users info.

The objective now is to get the 70+ ads shipped, so I'd say we display the "trouver des colis" button when the user is not logged.

Don't you think?

**Comment by AntonioVdlC** [comment]
Ok, fair enough!
I'll bundle that in the next release!
