### ISSUE TITLE
Design problem on the landing page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#41]
Design problem with the "livrer" button using a google chrome on the desktop.
Check the screenshot:
![image](https://user-images.githubusercontent.com/30872324/29244832-fc667f1e-7fc3-11e7-87d1-27dd42fcc8cf.png)

**Comment by AntonioVdlC** [comment]
Cannot reproduce ... I guess I solved it at some point because it is true I was adding the info icon on the next page and realised I broke the home page later on !

Good catch! 🙂
