### ISSUE TITLE
Add the label of the input on the landing page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#43]
Check the wireframe below:
![image](https://user-images.githubusercontent.com/30872324/29244931-0739ce92-7fc8-11e7-98d9-62865b9f7a1f.png)

**Comment by AntonioVdlC** [comment]
mmmh ... I'd rather leave this specific input without a label and a hint! 😅 

I'm open to it, but I feel like it breaks a bit the tightness and impact of the landing page!

**Comment by AntonioVdlC** [comment]
As discussed on Slack, we won't be adding that lil' label in here y'all!
