### ISSUE TITLE
User Profile - My certifications

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#44]
La page de verification des informations de profil

**Comment by AntonioVdlC** [comment]
Let me know when you are planning on testing the phone number validation so I can turn on some knobs on my side! 😝

**Comment by AntonioVdlC** [comment]
Also, let me know if you want to get any analytic events in the new user dashboard and user verifications screens!

**Comment by zuluzaire** [comment]
Events to add in the dashboard:
- Bouton Editer
- Bouton Faire verifier email
- Bouton Faire vérifier numéro
- Bouton voir mes colis

**Comment by zuluzaire** [comment]
Send a confirmation email when the user has verified an element of his profile, to confirm the user the element is verified.

In this email, invite the user to create an ad.

**Comment by AntonioVdlC** [comment]
Done! 🙂
