### ISSUE TITLE
Email user at ad creation

### ISSUE THREAD

**Issue by mupendara** [litomba/www#46]

**Comment by mupendara** [comment]
[Ad creation email.docx](https://github.com/litomba/www/files/1263602/Ad.creation.email.docx)

**Comment by mupendara** [comment]
See mail in attachment

**Comment by AntonioVdlC** [comment]
Oh, frère ... c'est ambitieux comme email là !

**Comment by mupendara** [comment]
Looool
Well just do an email with either the detailed information of the ad, or the summarised infor of the add.
And the a link to directly access to the ad page.

**Comment by AntonioVdlC** [comment]
In the emails, the links will be pointing to the prod instance for now, so they won't work in preprod but they'll be there.

**Comment by mupendara** [comment]
I've created an ad and i haven't received any email
