### ISSUE TITLE
Problem at access to landing page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#47]
When i access to landing page using the following address https://litomba-mvp.herokuapp.com/ on google chrome on the desktop, I am automatically redirected to the login/signup.
Once i am redirected, when i click on the home button, i have access to the landing page with no redirection on the signin/sign up page.

The redirection to the login page when i access to the landing page for the first time should be removed.

**Comment by AntonioVdlC** [comment]
That was probably due to some issues with the database migration ... I kind of screwed that part up a little bit sorry!
Let me know if you still have that problem!
