### ISSUE TITLE
Problem of size with the parcel picture

### ISSUE THREAD

**Issue by mupendara** [litomba/www#49]
In the ad creation form, the parcel picture uploaded should be displayed with a smaller size (about 2 or 3 times smaller for the maximum size).
I propose to use a standard size to display all the pictures (whatever the original picture size is).

See the screenshot:
![image](https://user-images.githubusercontent.com/30872324/29394062-43ff7afa-8308-11e7-83b1-f89f63c7e791.png)

**Comment by AntonioVdlC** [comment]
Yeah, I still have to look into how the whole app displays on wider screens ... it's not ideal, but the basic idea was for the picture to take all the available space.

I'll see what I can do!

**Comment by AntonioVdlC** [comment]
Reduce height of the picture (maybe use a thumbnail)!
