### ISSUE TITLE
Problem with the colours on the details ad page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#52]
On the details ad page, the red colour is used for the start address, and the green one for the end address.
Is it done on purpose?

I would do the opposite, green for start and red for the end.
Check screenshot:
![image](https://user-images.githubusercontent.com/30872324/29394364-fd940d54-8309-11e7-9320-9346b7250d17.png)

**Comment by AntonioVdlC** [comment]
That's on purpose!

At first I did it green-red, but then I looked at the logo, and in the logo it's red then green, so I thought it would make more sense that way, but this is an easy change, so let me know if you'd prefer it the other way round! 🙂
