### ISSUE TITLE
Problem with the size in the detailed ad page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#53]
On google chrome using the desktop:
On the details ad page, the size box is too big. The look and feel is so so....
Choose a less wide box

Check screenshot:
![image](https://user-images.githubusercontent.com/30872324/29394451-9dcdee34-830a-11e7-9962-ff4701dcd3b8.png)

**Comment by AntonioVdlC** [comment]
I'm adding this to the list of stuff I'll have to work on on wider screens ... 😅
