### ISSUE TITLE
Problem with the background colour of the size box

### ISSUE THREAD

**Issue by mupendara** [litomba/www#54]
The size box is filled with blue colour, it has been done on purpose?
I'd rather see the background in white instead of blue.

Check screenshot:
![image](https://user-images.githubusercontent.com/30872324/29394560-7d7f1dd2-830b-11e7-998c-02c72431b924.png)

**Comment by AntonioVdlC** [comment]
That is 100% done on purpose!
I can put a white background to the size box, but that way it reminds the color of the selected size in the creation page. 
Besides I does add some color to the page which is not a bad thing I think (but again, I ain't no designer so maybe it's just ugly!)
