### ISSUE TITLE
Add a default "value when empty" for the email field in the detailed ad page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#56]

**Comment by mupendara** [comment]
When the field "destinataire - email" is empty, a value when empty should displayed instead of nothing.
I propose to display "Aucun email indiqué"

Check screenshot:
![image](https://user-images.githubusercontent.com/30872324/29394789-ffdd6f26-830c-11e7-9b51-81bc72a8fed8.png)

**Comment by AntonioVdlC** [comment]
Instead of adding a default text, I think it's better to just don't show the field if the email or the phone was not filed!
