### ISSUE TITLE
Anchor problem in the ad creation page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#60]
On the mobile using google chrome, at access to ad creation page by clicking on "Livrer !" button, we are redirected to the ad creation page which is already scrolled down to a certain field. The title of the section "Colis" and the first field "Contenu du colis" are hidden. After the redirection, the ad creation page should not be scrolled so the user can see the title of the page etc. Remove the anchor.

**Comment by AntonioVdlC** [comment]
It ain't fixed!
