### ISSUE TITLE
Zoom the parcel picture from the details ad page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#73]
From the details ad page it should be possible to have an enlarged view of the parcel picture by clicking on the picture.
(proposition: an enlarged picture should be displayed in a modal window)

**Comment by zuluzaire** [comment]
Is it supposed to work on the mobile too?

**Comment by AntonioVdlC** [comment]
Yep, but only in the parcel details page (and it ain't pretty, I have to work on the styles a little bit more!).

**Comment by zuluzaire** [comment]
On the desktop it's possible to zoom the picture indeed, but the image zoom do not respect the original dimension of the picture
Check screenshots

Before zoom:
![image](https://user-images.githubusercontent.com/30872324/30152772-2f7a2fa8-93ac-11e7-9790-e20c326a109f.png)

After zoom:
![image](https://user-images.githubusercontent.com/30872324/30152790-409771e2-93ac-11e7-94a4-c57775951402.png)

**Comment by AntonioVdlC** [comment]
Yeah, this is ugly as shit ... I'll need to work on it a bit more!

**Comment by zuluzaire** [comment]
On my honor 7 mobile, once i have clicked on the picture to zoom in, when i click to exit the zoom display, my ad is totally empty. It happenned 2 or 3 times.
It seems to happen when my internet connexion is slow, because it doesnt happen all the time.

Check screenshot

**Comment by zuluzaire** [comment]
![screenshot_2017-09-07-15-11-55](https://user-images.githubusercontent.com/30872324/30167874-a9ef1d2e-93df-11e7-910e-6a070bca001a.png)
