### ISSUE TITLE
Ad visualization as creator

### ISSUE THREAD

**Issue by mupendara** [litomba/www#8]
Page to visualise parcel ad

**Comment by AntonioVdlC** [comment]
lol, je viens de me rendre compte qu'on a oublié de rajouter un champ pour le Titre / Contenu du colis sur la page de visualisation ... 😅

**Comment by AntonioVdlC** [comment]
Je l'ai rajouté comme ça, mais n'hésite pas si tu as une meilleure idée !

![localhost-3000-parcel-inin-uwxa5h6j nexus 5x](https://user-images.githubusercontent.com/5470315/29490692-c36e2ce0-8543-11e7-9e7b-319ccda135f9.png)
