### ISSUE TITLE
Impossible to save modifications on profile page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#80]
It's impossible to save modifications of the email address, the phone number and the birthday in the profile page.
When we click on "enregistrer" there is no confirmation message displayed and we we change the page and come back to the profile page the information modified have not been saved.

**Comment by mupendara** [comment]
When we make modifications on the on boarding page and then click on the save button, a saving confirmation message is displayed but modifications are not saved.
When i change page then go back on on boarding page, previous information is displayed.

**Comment by mupendara** [comment]
Problem still present, bug reopened

**Comment by AntonioVdlC** [comment]
Yeah, the bug was way deeper than I first thought ... 😅 

Hopefully now it works as expected!
