### ISSUE TITLE
Changing the user personal picture

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#81]
The user should be able to change his personal picture from the "mon profil" page

**Comment by zuluzaire** [comment]
When we change the profile picture, once we have selected the new picture (browsing in directories or taking a new picture) it takes a long time (around 10 seconds) to display the new picture on the my profile page.
During the 10 seconds, the message "Photo de profil incorrecte" is displayed, then around 10 seconds later, the photo is finally displayed.
It is disturbing because there is no loading indication during the 10 seconds, only the error message. And the error message is displayed as soon as we click on the "change button" at the beginning of the action.
It is disturbing behaviour.

**Comment by AntonioVdlC** [comment]
Argh ... that's a bug!
It should display a progress bar like in the ad creation page ... I'm on it! 👍

**Comment by zuluzaire** [comment]
Problem detected on the mobile, the progress bar is displayed in the same time as the error message "Photo de profil incorrecte".
I've just retested it, now when i change the picture, the progress bar loads during about 10 sec then the error message "Photo de profil incorrecte" is displayed with the button to chose the profile picture.

**Comment by zuluzaire** [comment]
Performance problem at the upload of a new profile picture.
Check the network statistics below:

**Comment by AntonioVdlC** [comment]
I'm already resizing the image before upload ... 🤔 
I guess I can always reduce its size even more, but I think the bottleneck here is your connection 😅 

![image](https://user-images.githubusercontent.com/5470315/30170860-899841d4-93f0-11e7-8cfd-a7a0d5419507.png)
