### ISSUE TITLE
Seperation bar missing in the header dropping menu

### ISSUE THREAD

**Issue by mupendara** [litomba/www#84]
Seperation bar between "envoyer un colis" et "mes colis" missing.
Check screenshot off mobile version
![screenshot_2017-08-26-01-43-42](https://user-images.githubusercontent.com/30872324/29737102-418f08e0-8a00-11e7-90bc-715705f47e0f.png)

**Comment by AntonioVdlC** [comment]
mmmh ... that was made on purpose! 😅 

The idea was to separate the Profile from a series of other actions (My Parcels / Create Parcel Ad) and then the Logout.

I can add a separator if you prefer!
