### ISSUE TITLE
Change the font of the website

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#89]
Use a more smooth font for litomba web application.
Use Airbnb font for example (Charter regular, Calibre medium, Calibre semibold) 
Or the "lineto-circular" fonts, you will find it in the following site: www.jobsite.co.uk

**Comment by AntonioVdlC** [comment]
All of those are paying fonts ... I chose another font that is free, but let me know if you find a better one in here: https://fonts.google.com/
