### ISSUE TITLE
Parcel ads search

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#9]
Page to search parcel ads

**Comment by AntonioVdlC** [comment]
Should be accessible without connection!

**Comment by zuluzaire** [comment]
The connection is still requested to access to the ads search

**Comment by AntonioVdlC** [comment]
Oh ok, my bad!
I thought we were restricting the search to logged-in users ... 😅 

It should be an easy change tough! 🙂

**Comment by AntonioVdlC** [comment]
Ok, after a little more reflexion I'm gonna contradict my past self ... I think we shouldn't make this accessible without login ! 😅

**Comment by zuluzaire** [comment]
Why ??

**Comment by AntonioVdlC** [comment]
Ok done!
Still need to log in to visualize the parcel details though! 😛
