### ISSUE TITLE
Performance problem at access to "my ads" page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#90]
On the desktop, the "my ads" page takes too long to be displayed (around 2 minutes).
Check the network screenshots below:
![image](https://user-images.githubusercontent.com/30872324/29740665-ab421194-8a53-11e7-9cbf-efd80bfb1c6b.png)

**Comment by AntonioVdlC** [comment]
This is due to #71 as it is trying to download a pretty big image that was previously uploaded!

Reducing the size of images before upload should solve both issues!
