### ISSUE TITLE
Geofence destination autocomplete to Africa

### ISSUE THREAD

**Issue by AntonioVdlC** [litomba/www#93]
We are exclusively focusing on the African market, so it makes sense to restrict destinations to Africa! 🌍

**Comment by mupendara** [comment]
When the user select a destination address which is not in africa, the error message "Veuillez saisir une addresse correcte." is not explicit enough
We should display in the error message that the destination address should be in africa.

**Comment by AntonioVdlC** [comment]
I updated the error message to be more explicit about the geo-restrictions that apply to the destination address!

**Comment by mupendara** [comment]
solved
