### ISSUE TITLE
Why is the google maps component in english language?

### ISSUE THREAD

**Issue by mupendara** [litomba/www#96]
The google maps component displays values in english and not in french.
Is it linked to my google account, browser configuration ?

Check screenshot
![image](https://user-images.githubusercontent.com/30872324/29874109-a8476a7e-8d8d-11e7-9b94-0cc49e4f42ae.png)

**Comment by AntonioVdlC** [comment]
According to the docs:

```
"The API detects the browser settings of the user and set the language appropriately. It is possible to override the language in the APIs."
```

So if your browser is in English it'll show the results in English.

We can force it to always be in French, but I feel like we'll roll out an English version of litomba sometime soon anyway, so I think it's good that we keep the current behaviour on this one!

**Comment by mupendara** [comment]
Ok perfect, just wanted to make sure
