### ISSUE TITLE
Problem of font on the ad creation page

### ISSUE THREAD

**Issue by mupendara** [litomba/www#98]
The page used in the description field of the ad creation is different from all the other fonts used.
Check screenshot
![image](https://user-images.githubusercontent.com/30872324/29874373-73aaa47e-8d8e-11e7-94d6-688c638435ab.png)

**Comment by AntonioVdlC** [comment]
Which browser is that on?

I can't reproduce on Chrome on macOS ... 🤔

**Comment by mupendara** [comment]
It was on desktop chrome and Firefox

**Comment by AntonioVdlC** [comment]
Ok, I could reproduce it in Firefox, but I don't have that problem in Chrome on macOS ... 😅 

I may have to look into finding a way to develop on Windows, because there seems to still be quite some inconsistency.

**Comment by mupendara** [comment]
solved
