### ISSUE TITLE
Problem at ad creation regarding the destination address

### ISSUE THREAD

**Issue by mupendara** [litomba/www#99]
Some destination addresses are refused at ad creation.

Check screenshot
![image](https://user-images.githubusercontent.com/30872324/29874474-c8b92472-8d8e-11e7-82d9-888f315d2565.png)

**Comment by AntonioVdlC** [comment]
Can't reproduce!

Trying the same exact address seems to work just fine, so this has probably been fixed in the meantime! Let me know if that happens again!

**Comment by mupendara** [comment]
solved
